# Generated by Django 4.1 on 2022-09-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
